basePath: /
definitions:
  handler.AddSegmentRequest:
    properties:
      percentage:
        type: integer
      slug:
        type: string
    required:
    - slug
    type: object
  handler.DeleteSegmentRequest:
    properties:
      slug:
        type: string
    required:
    - slug
    type: object
  handler.UpdateUserSegmentsRequest:
    properties:
      delete_at:
        type: integer
      slugs_to_add:
        items:
          type: string
        type: array
      slugs_to_del:
        items:
          type: string
        type: array
      user_id:
        type: integer
    required:
    - slugs_to_add
    - slugs_to_del
    - user_id
    type: object
host: localhost:8080
info:
  contact: {}
  description: User Segmentation Service
  title: Avito Trainee Assignment 2023
  version: "1.0"
paths:
  /segment/add:
    post:
      consumes:
      - application/json
      description: Add new segment with specified slug
      parameters:
      - description: segment slug
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.AddSegmentRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Add Segment
      tags:
      - segment
  /segment/delete:
    delete:
      consumes:
      - application/json
      description: Delete segment with specified slug
      parameters:
      - description: segment slug
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.DeleteSegmentRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete Segment
      tags:
      - segment
  /user/{user_id}:
    get:
      consumes:
      - application/json
      description: Get active segments for specified user
      parameters:
      - description: user ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get User Segments
      tags:
      - user
  /user/history/{user_id}:
    get:
      consumes:
      - application/json
      description: Get user segments history
      parameters:
      - description: user ID
        in: path
        name: user_id
        required: true
        type: integer
      - description: month
        in: query
        name: month
        required: true
        type: integer
      - description: year
        in: query
        name: year
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get User History
      tags:
      - user
  /user/segment:
    put:
      consumes:
      - application/json
      description: Update user segments with specified slugs for specified user
      parameters:
      - description: user and segments info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateUserSegmentsRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update User Segments
      tags:
      - user
swagger: "2.0"
